symlinks:

  # Sample folder
  - src: ..\packages\jp.co.hololab.positioningtools\Samples~
    dest: ..\unity\PositioningTools\Assets\PositioningTools.Samples
  - src: ..\packages\jp.co.hololab.positioningtools.arcoreextensions\Samples~
    dest: ..\unity\PositioningTools-ARCore-GeospatialAPI\Assets\PositioningTools.ARCoreExtensions.Samples